### ISSUE TITLE
Mavlink Sensor Error

### ISSUE THREAD

**Issue by cam-s-hunt** [cam-s-hunt/osh-node-dev-template#1]
In the UI:

![image](https://github.com/cam-s-hunt/osh-node-dev-template/assets/44948425/67b04f10-3477-462d-b884-30543e00a23e)

From the console:

2023-06-19 15:42:36.066 ERROR AdminUIModule:125edb9e [qtp534695842-47] - Unexpected error when selecting module
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final long java.util.RegularEnumSet.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @4a94ee4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at NativeClassLoader//com.rits.cloning.Cloner$CloneObjectCloner.<init>(Cloner.java:590)
	at NativeClassLoader//com.rits.cloning.Cloner.findDeepCloner(Cloner.java:485)
	at NativeClassLoader//com.rits.cloning.Cloner.cloneInternal(Cloner.java:449)
	at NativeClassLoader//com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:663)
	at NativeClassLoader//com.rits.cloning.Cloner.access$1300(Cloner.java:26)
	at NativeClassLoader//com.rits.cloning.Cloner$CloneObjectCloner.deepClone(Cloner.java:635)
	at NativeClassLoader//com.rits.cloning.Cloner.cloneInternal(Cloner.java:457)
	at NativeClassLoader//com.rits.cloning.Cloner.deepClone(Cloner.java:348)
	at NativeClassLoader//org.sensorhub.utils.ConfigCloner.deepClone(ConfigCloner.java:59)
	at NativeClassLoader//org.sensorhub.api.module.ModuleConfig.clone(ModuleConfig.java:64)
	at NativeClassLoader//org.sensorhub.ui.AdminUI.selectModule(AdminUI.java:1094)
	at NativeClassLoader//org.sensorhub.ui.AdminUI$10.itemClick(AdminUI.java:670)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at NativeClassLoader//com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706)
	at NativeClassLoader//com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
	at NativeClassLoader//com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
	at NativeClassLoader//com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1190)
	at NativeClassLoader//com.vaadin.v7.ui.Table.handleClickEvent(Table.java:3154)
	at NativeClassLoader//com.vaadin.v7.ui.Table.changeVariables(Table.java:2948)
	at NativeClassLoader//com.vaadin.v7.ui.TreeTable.changeVariables(TreeTable.java:434)
	at NativeClassLoader//com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:616)
	at NativeClassLoader//com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:468)
	at NativeClassLoader//com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:411)
	at NativeClassLoader//com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275)
	at NativeClassLoader//com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
	at NativeClassLoader//com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at NativeClassLoader//com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)
	at NativeClassLoader//com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
	at NativeClassLoader//org.sensorhub.ui.AdminUIServlet.service(AdminUIServlet.java:53)
	at NativeClassLoader//javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at NativeClassLoader//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at NativeClassLoader//org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	at NativeClassLoader//org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at NativeClassLoader//org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at NativeClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at NativeClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at NativeClassLoader//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at NativeClassLoader//org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at NativeClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at NativeClassLoader//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at NativeClassLoader//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at NativeClassLoader//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at NativeClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at NativeClassLoader//org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at NativeClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at NativeClassLoader//org.eclipse.jetty.server.Server.handle(Server.java:516)
	at NativeClassLoader//org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at NativeClassLoader//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at NativeClassLoader//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at NativeClassLoader//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at NativeClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at NativeClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at NativeClassLoader//org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at NativeClassLoader//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at NativeClassLoader//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at NativeClassLoader//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at NativeClassLoader//org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at NativeClassLoader//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at NativeClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at NativeClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nickgaray** [comment]
I had run into this issue earlier with newer versions of Java.  Apparently you need to use the --add-opens switch for runtime.  Here is a link for more information on the switch.

https://www.oreilly.com/library/view/java-9-building/9781788832823/40494528-393d-49e4-a216-d7a2d4d7e95c.xhtml#:~:text=This%20allows%20the%20given%20module,the%20O'Reilly%20learning%20platform.

Here is another article:
https://help.mulesoft.com/s/article/What-is-JDK-JAVA-OPTIONS--add-opens-in-wrapper-conf-used-for
